title: Diego Boscan - Desarrollador
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador web full stack, especializado en JavaScript y su ecosistema
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diegoboscan.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Diego Boscan # add your name
author-img: diego.jpg # add your photo
about-author: Desarrollador autodidacta, apasionado por lo que hago # add description

social-github: dboscanv # add your Github handle
social-linkedin: diego-boscan-586b16108 # add your Linkedin handle
social-email: dboscanv@gmail.com # add your Email address

# Disqus
discus-identifier: diegoboscan # add your discus identifier

# Tracker
analytics: UA-123744687-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed


paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
